name: PHP CI
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [5.6, 7.0, 7.1, 7.2, 7.3, 7.4]

    steps:
      - name: Install additional packages
        run: sudo apt-get install -y stunnel

      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Setup PHP
        uses: shivammathur/setup-php@86e1ccdd8ddc47bffc29bf667143f363a4cdfdbc
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
    
      - name: Composer install
        run: composer install
   
      - name: PHP tests
        run: ./vendor/bin/phpunit
